SELECT ENTRYBOARD_SEQ.NEXTVAL FROM DUAL;


SELECT EMP_ID, EMP_NAME || ' - ' || (SELECT RANK_NAME FROM "RANK" r WHERE r.RANK_NO =e.RANK_NO) AS EMP_NAME , DEPT_NO, RANK_NO 
	FROM EMP e
		ORDER BY RANK_NO DESC		
		
SELECT APPRO_NO, a.APPRO_LINE_NO, DOC_FORM_NO, EMP_ID, APPRO_EMPNAME, APPRO_TITLE, APPRO_CONTENT, APPRO_REGDATE, APPRO_STATUS, APPRO_STATUS_NO, APPRO_TYPE, APPRO_REFER, APPRO_RETURNREASON
	FROM ADMIN.APPROVAL a JOIN APPROVAL_LINE al
	ON al.APPRO_LINE_NO = a.APPRO_LINE_NO  
		WHERE a.APPRO_NO = 'DOIT-2022053121'
		
SELECT EMP_ID ,EMP_NAME ,RANK_NO ,e.DEPT_NO , d.DEPT_NAME 
	FROM EMP e JOIN  DEPT d 
	ON e.DEPT_NO = d.DEPT_NO 
		WHERE e.EMP_ID  = 2022052800		

		--폼		
INSERT INTO ADMIN.DOCUMENT_FORM
(DOC_FORM_NO, DOC_FORM_TEMPLATE, DOC_FORM_DATE, DOC_FORM_NAME)
VALUES('DOC0000', '', CURRENT_DATE, 'SAMPLE');

--기본 사인 이미지 없는 사원에게 기본서명이미지 등록해주는 쿼리
INSERT INTO ADMIN.SIGN
(SIGN_NO, EMP_ID, SIGN_REGDATE, SIGN_NAME, SIGN_IMG)
VALUES(8,2022053600, CURRENT_DATE, (SELECT SIGN_NAME FROM SIGN s WHERE EMP_ID= 1004), (SELECT SIGN_IMG FROM SIGN s WHERE EMP_ID= 1004));
