SELECT ENTRYBOARD_SEQ.NEXTVAL FROM DUAL;

SELECT a.APPRO_NO ,a.APPRO_LINE_NO ,ap.EMP_ID , ap.APPRO_STATUS , ap.APPRO_INFO ,TO_NUMBER(ROW_NUMBER) RM 
FROM APPROVAL_LINE al ,(SELECT APPRO_NO,APPRO_LINE_NO  FROM APPROVAL a) a ,JSON_TABLE(APPRO_LINE, '$.approval[*]'
	COLUMNS(
			ROW_NUMBER FOR ORDINALITY,
			EMP_ID VARCHAR2(100)  PATH '$.EMP_ID',
			APPRO_INFO VARCHAR2(100) PATH '$.APPRO_NAME',
			APPRO_STATUS VARCHAR2(100) PATH '$.APPRO_STATUS')) AS ap
WHERE al.APPRO_LINE_NO = a.APPRO_LINE_NO AND ap.EMP_ID = #{emp_id}

ALTER TABLE EMP ADD SIGN_NAME VARCHAR2(100) DEFAULT '기본서명.png' NOT NULL;

SELECT * FROM EMP;