SELECT ENTRYBOARD_SEQ.NEXTVAL FROM DUAL;


SELECT EMP_ID, EMP_NAME || ' - ' || (SELECT RANK_NAME FROM "RANK" r WHERE r.RANK_NO =e.RANK_NO) AS EMP_NAME , DEPT_NO, RANK_NO 
	FROM EMP e
		ORDER BY RANK_NO DESC		
		
SELECT APPRO_NO, a.APPRO_LINE_NO, DOC_FORM_NO, EMP_ID, APPRO_EMPNAME, APPRO_TITLE, APPRO_CONTENT, APPRO_REGDATE, APPRO_STATUS, APPRO_STATUS_NO, APPRO_TYPE, APPRO_REFER, APPRO_RETURNREASON
	FROM ADMIN.APPROVAL a JOIN APPROVAL_LINE al
	ON al.APPRO_LINE_NO = a.APPRO_LINE_NO  
		WHERE a.APPRO_NO = 'DOIT-2022053121'
		
SELECT EMP_ID ,EMP_NAME ,RANK_NO ,e.DEPT_NO , d.DEPT_NAME 
	FROM EMP e JOIN  DEPT d 
	ON e.DEPT_NO = d.DEPT_NO 
		WHERE e.EMP_ID  = 2022052800		